# Generated by Django 2.2 on 2019-12-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots_app', '0005_auto_20191222_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='desc',
            field=models.CharField(max_length=120),
        ),
    ]
