# Generated by Django 2.2 on 2019-12-26 23:18

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots_app', '0007_auto_20191226_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='django-skate-spots'), upload_to=''),
        ),
    ]
